index.html, package-lock.json, package.json
- 그냥 npm run dev 를 하면 에러 생김
- npm에 postcss-nesting 인스톨했음
- 인스톨 후 npm run dev 를 하면 에러가 생기지 않음
어떤 변경 사항이 있나요?
=> feat : postcss-nesting install

src/pages/login/index.html
=> login 환경 설정 완료

src/pages/start/index.html
=> modify : start css 코드 수정 - iamjinpark

.env
=> feat : Delete .env - taewook

src/pages/board/index.html, src/styles/tailwind.css
=> docs : githistory 제거 - taewook

.gitignore
=> docs : gitignore 추가 - taewook

src/pages/profile/index.html, vite.config.js
feat: profile 페이지 문법 오류 수정 및 vite.config 경로 추가 
어떤 변경 사항이 있나요?
=> feat: profile 페이지 문법 오류 수정 및 vite.config 경로추가-vhwav

public/images/plusTap.svg, public/images/plusTapActive.svg, src/pages/togetherBoard/index.html
=> feat : togetherBoard에 plusTap 버튼 추가 - taewook

src/pages/board/index.html
modify: board 페이지 마크업 수정,선택자 생성 - taewook
어떤 변경 사항이 있나요?
=> modify: board 페이지 마크업 수정,선택자 생성 - taewook

src/pages/togetherBoard/index.html
modifiy: togetherBoard 마크업 수정, figure를 button으로 변경 - taewook
어떤 변경 사항이 있나요?
=> modifiy: togetherBoard 마크업 수정, figure를 button으로 변경 - taewook

vite.config.js
- 디렉토리 위치 문제 및 내용 중복 수정
closed #76 
어떤 변경 사항이 있나요?
=> fixs : vite.config 내용 수정

src/pages/signUp/index.html
뒤로가기 img를 a가 아닌 버튼으로 마크업
어떤 변경 사항이 있나요?
=> Modify : 뒤로가기 버튼 태그로 수정 - iamjinpark

src/pages/writeBoard/index.html
modify:writeBoard 페이지의 h1 sr-only 수정-taewook
어떤 변경 사항이 있나요?
- [x ] 코드 리팩토링
- [x ] 커밋 메시지 컨벤션에 맞게 작성했습니다. Commit message convention 참고 (Ctrl + 클릭하세요.)
- [x ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> modify:writeBoard 페이지의 h1 sr-only 수정-taewook

src/pages/category/index.html, src/styles/tailwind.css, vite.config.js
뒤로가기 a 에서 button으로 태그 수정 -> 추후 자바스크립트로 제어 예정
className 수정 / tailwind.css 동시 수정
lnput 태그에 label 태그 연결 
어떤 변경 사항이 있나요?
=> Modify : 뒤로가기 태그 및 className 수정 - iamjinpark

src/pages/login/index.html
사라진 로그인 페이지 다시 pr
어떤 변경 사항이 있나요?
=> feat : login 페이지 구현 - iamjinpark

vite.config.js
vite.config에 login 페이지 추가
어떤 변경 사항이 있나요?
=> docs : vite.config에 login 페이지 추가 - iamjinpark

src/pages/writeBoard/index.html
feat: writeboard container 통합 작업 - vHwav
어떤 변경 사항이 있나요?
#93
=> feat: writeboard container 통합 작업 

public/images/fullheart.svg, src/pages/chat/index.html, src/pages/components/boardNav/index.html, src/pages/components/headNav/index.html, src/pages/components/homeNav/index.html, src/pages/exchange/index.html, src/pages/exchangeBoard/index.html, src/pages/story/index.html, src/styles/tailwind.css
- homeNav, headNav 수정
- boardNav 추가
- component 에 들어갈 문서들 수정
#97
어떤 변경 사항이 있나요?
=> feat : component 수정

public/images/checked.svg, src/pages/category/category.js, src/pages/category/index.html, src/styles/tailwind.css
이미지였던 plus 아이콘을 버튼으로 수정,
클릭시 checked로 바뀔 수 있게 svg 추가,
버튼 이벤트를 위한 category-button-active 클래스 추가
어떤 변경 사항이 있나요?
=> modify : plus 아이콘 img -> button으로 수정 -iamjinpark

src/pages/chatScreen/index.html, src/pages/togetherBoard/index.html
modify: +버튼에 bg-background 추가 - taewook
어떤 변경 사항이 있나요?
=> modify: +버튼에 bg-background 추가 - taewook

src/pages/signUp/index.html, src/pages/signUp/signUp.js
w-screen 추가해서 한 페이지 내에 두페이지 이동 가능하게 수정
js 코드 추가로 이동 기능 구현
어떤 변경 사항이 있나요?
=> modify : w-screen 추가 및 js로 페이지 이동 구현 - iamjinpark

src/pages/signUp/index.html, src/pages/signUp/signUp.js
뒤로가기 버튼 a 에서 button으로 수정 후 자바스크립트 history.back() 추가
어떤 변경 사항이 있나요?
=> modify : 뒤로가기 버튼 a -> button 으로 수정 - iamjinpark

src/pages/profile/index.html, src/pages/profileCard/index.html, src/pages/profileDetails/index.html
feat: page 연결 및 profile 의 figure>div로 변경 - vHwav
어떤 변경 사항이 있나요?
=> feat: page 연결 및 profile 의 figure>div로 변경 - vHwav

src/pages/exchange/exchange.js, src/pages/exchange/index.html, src/pages/exchangeBoard/exchangeBoard.js, src/pages/exchangeBoard/index.html, src/styles/tailwind.css
- exchangeBoard 좋아요
- exchange 작성하기 추가
#116
어떤 변경 사항이 있나요?
=> feat : 버튼 기능 추가

src/pages/components/headNav/index.html, src/pages/components/homeNav/index.html, src/pages/exchange/exchange.js, src/pages/exchange/index.html, src/pages/exchangeBoard/index.html, src/pages/search/index.html, src/pages/story/index.html, vite.config.js
- 페이지 간 링크 연결
- ui 간격 및 크기 조절
#119 
어떤 변경 사항이 있나요?
=> modify : 중간점검 전 수정

src/pages/togetherBoard/index.html
bug:버그체크하자 - taewook
어떤 변경 사항이 있나요?
=> bug:버그체크하자 - taewook

package-lock.json, package.json, vite.config.js
- reset 으로 인한 setting 초기화
- rollup 설치
- vite.config.js rollup 내용추가
어떤 변경 사항이 있나요?
=> feat : setting 초기화 01.09 16:56

src/pages/components/headNav/index.html, src/pages/exchange/exchange.js, src/pages/exchange/index.html, src/pages/exchangeBoard/exchangeBoard.js, src/pages/exchangeBoard/index.html, src/pages/search/index.html, src/pages/story/index.html
- 초기화 하면서 없어진 코드 복구
- exchange.js, exchangeBoard.js
- innerHTML 삭제
어떤 변경 사항이 있나요?
=> docs : 문서 복원 01-09 21:14

src/pages/category/category.js, src/pages/category/index.html, src/styles/tailwind.css, tailwind.config.js
div 태그에서 탭 키 접근 안되는 문제 발생 -> label, input태그로 변경
자바스크립트 기능 추가 -> 플러스 클릭 시 체크 아이콘으로 변경, 배경색 변경
어떤 변경 사항이 있나요?
=> modify : 마크업 수정 및 hover 이벤트 추가 - iamjinpark

src/pages/exchange/exchange.js, src/pages/exchangeBoard/exchangeBoard.js, src/pages/exchangeBoard/index.html
feat : exchangeBoard 기능 추가
- get 상품정보
- 본 글 상품정보
- 함께 봤어요 상품정보 4개까지 보이게 추가
#116
어떤 변경 사항이 있나요?
=> feat : exchangeBoard 기능 추가 01-10 15:57

src/pages/profile/index.html, src/pages/profile/profile.js, src/pages/profileCard/index.html, src/pages/profileCard/profileCard.js, src/pages/profileDetails/index.html, src/pages/profileDetails/profileDetails.js, src/styles/tailwind.css
profile list 구현 및, 전체 homeNav 위치 수정 18:06 -vHwav-
어떤 변경 사항이 있나요?
=> profile list 구현 및, 전체 homeNav 위치 수정 18:06 -vHwav-

src/lib/utils/index.js, src/lib/utils/removeChild.js, src/pages/exchangeBoard/exchangeBoard.js, src/pages/exchangeBoard/index.html
modify : 링크 연결 수정
- exchangeBoard 에서 이 글과 함께 봤어요 부분 링크 안눌리는거 해결
#116
어떤 변경 사항이 있나요?
=> modify : 링크 연결 수정 01-11 09:05

src/pages/exchange/exchange.js, src/pages/exchange/index.html, src/pages/exchangeBoard/exchangeBoard.js
modify : 반복되는 함수 forEach
- 버튼의 EventListener 반복
- forEach, 구조분해할당 등으로 축약
#116
어떤 변경 사항이 있나요?
=> modify : 반복되는 함수 forEach 01-11 11:26

src/pages/signUp/index.html, src/pages/signUp/signUp.js
핸드폰 번호 유효성 검사 및 valid 상태,
localStorage에 저장 후 다음 페이지 화면에 랜더링 기능 구현
어떤 변경 사항이 있나요?
=> feat : 핸드폰 번호 valid 및 localStorage 저장 기능 구현 - iamjinpark

src/pages/board/board.js, src/pages/board/index.html, src/pages/boardContent/index.html, src/pages/chatScreen/index.html, src/pages/togetherBoard/index.html, src/pages/togetherBoard/togetherBoard.js, src/pages/writeBoard/index.html
feature: board 쪽 페이지들 min-280px 조절, 같이해요 페이지 nav toggle 수정 및 구현 -taewook 01/11오후5:42
어떤 변경 사항이 있나요?
=> feature: board 쪽 페이지들 min-280px 조절, 같이해요 페이지 nav toggle 수정 및 구현 -taewook 01/11오후5:42

src/pages/signUp/index.html, src/pages/signUp/signUp.js
체크 기능 및 로컬스토리지 저장 기능 구현 완료
어떤 변경 사항이 있나요?
=> feat : valid 체크 기능 및 로컬스토리지 저장 기능 구현 완료 - iamjinpark 01/12 3:17am

package-lock.json, package.json, src/pages/profile/index.html, src/pages/profile/profile.js, src/pages/profileDetails/index.html, src/pages/profileDetails/profileDetails.js
feat:profile,profileDetails데이터세팅 03:16 -vHwav
어떤 변경 사항이 있나요?
=> feat:profile,profileDetails데이터세팅 03:16 -vHwav

src/pages/signUp/signUp.js
pocketbase post 기능 구현
어떤 변경 사항이 있나요?
=> feat : pocketbase post 기능 구현 - iamjinpark 01/12 4:31am

src/pages/signUp/signUp.js
회원가입 휴대폰번호 중복 검사 기능 구현
중복인 번호의 경우 로그인 페이지로 전환
어떤 변경 사항이 있나요?
=> feat : 회원가입 중복 유효성 검사 구현 완료 - iamjinpark 01/12 1:47pm

src/pages/board/board.js, src/pages/board/index.html, src/pages/boardContent/boardContent.js, src/pages/togetherBoard/index.html, src/pages/togetherBoard/togetherBoard.js, src/pages/writeBoard/index.html, src/pages/writeBoard/writeBoard.js
feature: 다른페이지 ui 수정, writeBoard 입력UI선택작업중 -taewook 01/12오후3:55
1. board, togetherBoard 페이지 ui 수정
2. writeBoard 페이지 사용자 입력 ui 코드 구현 (아직 이쁘지않음)
3. writeBoard.js 에 pb create로 우선 고정 값으로 함수 넣음 (우선은 고정값으로 commnunity레코드에 게시물 create 구현)
4. 사용자가 입력해준 데이터로 받을 예정
어떤 변경 사항이 있나요?
=> feature: 다른페이지 ui 수정, writeBoard 입력UI선택작업중 -taewook 01/12오후3:55

src/pages/exchangePost/exchangePost.js, src/pages/exchangePost/index.html
feat : post 기능 구현
- 이미지, 제목, 카테고리, 가격, 내용, 동네 post
#116
어떤 변경 사항이 있나요?
=> feat : post 기능 구현 01-12 22:10

src/lib/utils/formattedDate.js, src/lib/utils/formattedTime.js, src/lib/utils/index.js, src/pages/togetherBoard/togetherBoard.js, src/pages/writeBoard/index.html, src/pages/writeBoard/writeBoard.js
feature: writeboard  게시글 create 구현  -taewook 01/13 오전1:24
1. 나이 선택 및 다른 입력 ui 수정예정 .
2.  데이터 뿌리는 화면 수정예정
어떤 변경 사항이 있나요?
=> feature: writeboard  게시글 create 구현 나이선택제외 -taewook 01/13 오전1:24

src/lib/utils/formattedDate.js, src/pages/board/board.js, src/pages/togetherBoard/togetherBoard.js
feature: togetherpage gsap적용 -taewook 01/13 오전3:43
1. togetherBoard page gsap 적용해서 게시글 랜더링
2. board, togertherBoard 페이지 값들 수정
어떤 변경 사항이 있나요?
=> feature: togetherpage gsap적용 -taewook 01/13오전3:43

src/pages/login/index.html, src/pages/login/login.js, src/pages/signUp/signUp.js
1. 정규식 통해 핸드폰 번호 유효성 검사
2. pb 데이터값과 일치 여부 확인 통해 로그인/회원가입 분류
3. localStorage 저장
4. 인증번호 받기 기능 구현
어떤 변경 사항이 있나요?
=> feat : 로그인 필수 기능 구현 완료 - iamjinpark 01/13 3:44am

src/lib/dom/insert.js, src/pages/profile/profile.js, src/pages/profileCard/index.html, src/pages/profileDetails/index.html, src/pages/profileDetails/profileDetails.js
feat:profile리스트 정리  05:39 -vHwav
어떤 변경 사항이 있나요?
=> feat:profile리스트 정리  05:39 -vHwav

src/lib/utils/debounce.js, src/lib/utils/index.js, src/pages/profile/profile.js, src/pages/profileCard/index.html, src/pages/profileCard/profileCard.js, src/styles/tailwind.css
feat:profileCard 수정기능 구현 중간 저장 13:53 -vHwav-
어떤 변경 사항이 있나요?
=> feat:profileCard 수정기능 구현 중간 저장 13:53 -vHwav-

src/pages/boardContent/boardContent.js, src/pages/boardContent/index.html, src/pages/chatScreen/chatScreen.js, src/pages/chatScreen/index.html, src/pages/togetherBoard/index.html, src/pages/togetherBoard/togetherBoard.js
feature: 같이해요deatils 화면 연동, delete 구현중 taewook 오후4:39
more 버튼 드롭다운메뉴 설정 (다른곳 클릭 시 적용 못함)
어떤 변경 사항이 있나요?
=> feature:같이해요deatils 화면연동, delete 구현중 taewook 오후4:39

src/lib/utils/index.js, src/lib/utils/rendering.js, src/pages/profileCard/index.html, src/pages/profileCard/profileCard.js, vite.config.js.timestamp-1705146579082-6193cd50cdd2d.mjs
feat: rendering util함수 추가 및 profileCard 기능 구현 00:46 -vHwav
어떤 변경 사항이 있나요?
=> feat: rendering util함수 추가 및 profileCard 기능 구현 00:46 -vHwav

src/pages/exchangeBoard/exchangeBoard.js
feat : 좋아요 연동 구현
- 각 사용자마다 좋아요 동기화
#116
어떤 변경 사항이 있나요?
=> feat : 좋아요 연동 구현 01-14 04:00

src/pages/exchangeBoard/exchangeBoard.js, src/pages/exchangeBoard/index.html, src/pages/exchangeEdit/exchangeEdit.js, src/pages/exchangeEdit/index.html
feat : 좋아요 연동 수정
- 일부 리펙토링 및 주석 삭제
- exchangeBoard 에 누가 글 쓴지 연동
- 더보기 클릭 활성화
- 유저가 글쓴이 인지, 일반 뷰어인지에 따라 더보기 내용 바뀜
- exchangeEdit 작성중
#116
어떤 변경 사항이 있나요?
=> feat : 좋아요 연동 수정 01-14 07:57

src/pages/category/index.html, src/pages/signUp/index.html, src/pages/signUp/signUp.js
정규식 유효성 검사 및 타이머 기능 추가 
어떤 변경 사항이 있나요?
=> feat : 정규식 유효성 검사 수정 및 타이머 기능 추가 - iamjinpark 01/14 6:00pm

src/pages/exchange/exchange.js, src/pages/exchange/index.html, src/pages/exchangeBoard/exchangeBoard.js, src/pages/exchangeBoard/index.html, src/pages/exchangeEdit/exchangeEdit.js, src/pages/exchangeEdit/index.html, src/styles/tailwind.css
feat : 좋아요 갯수 연동 및 update페이지 구연
- 각 아이템 마다의 좋아요 갯수를 랜더링
- update 페이지 기능 구현
#116
어떤 변경 사항이 있나요?
=> feat : 좋아요 갯수 연동 및 update페이지 구연 10-14 18:40

src/pages/signUp/index.html, src/pages/signUp/signUp.js
=> feat : 타이머 기능 구현 완료 - iamjinpark 01/14 7:32pm

src/lib/utils/getPbImageURL.js, src/lib/utils/rendering.js, src/pages/profile/index.html, src/pages/profile/profile.js, src/pages/profileCard/index.html, src/pages/profileCard/profileCard.js, src/pages/signUp/index.html, src/pages/signUp/signUp.js
feat: getPbImageURL경로 수정 및 renderingPhoto 추가 19:51 -vHwav
어떤 변경 사항이 있나요?
=> feat: getPbImageURL경로 수정 및 renderingPhoto 추가 19:51 -vHwav

src/lib/utils/rendering.js, src/pages/profileCard/index.html, src/pages/profileCard/profileCard.js
feat: profileCard 에러 수정 21:21 -vHwav
어떤 변경 사항이 있나요?
=> feat: profileCard 에러 수정 21:21 -vHwav

src/lib/utils/getPbImageURL.js
- 경로 설정 오류로 인한 수정
어떤 변경 사항이 있나요?
=> modify : getPbImageURL.js 01-14 21:42

src/pages/category/category.js, src/pages/category/index.html
관심분야 로컬스토리지에 저장 및 포켓베이스로 전송
어떤 변경 사항이 있나요?
=> feat : 로컬스토리지 저장 및 포켓베이스 post 기능 구현 - iamjinpark 01/15 3:35am

src/pages/togetherBoard/togetherBoard.js
feature:같이해요페이지 filter구현 -taewook 01/15 오전9:30
1. 뿌려지는 속도가 느려서 우선 serTimeout()함수를 줬습니다.
어떤 변경 사항이 있나요?
=> feature:같이해요페이지 filter구현 -taewook 01/15 오전9:30

src/pages/board/board.js, src/pages/board/index.html, src/pages/boardContent/boardContent.js, src/pages/boardContent/index.html, src/pages/togetherBoard/index.html, src/pages/togetherBoard/togetherBoard.js, src/pages/writeBoard/index.html, src/pages/writeBoard/writeBoard.js, tailwind.config.js
feature:포커스색변환, 같이해요드롭다운메뉴 -taewook 01/15오후1:04
1. 마우스 focus 시 색 변환
2. writeBoard.js 같이해요부분 카테고리 선택 드롭다운메뉴 수정
3. tailwind.config.js 에 focus 기능 추가 (이제 html파일에 inline으로 적용가능)
4. 글자크기 조절
5. board 페이지 부분 nav바에 주제, 같이해요 focus 시 살짝 커짐
6. 같이해요 게시물 : 버튼 누를 시 드롭다운메뉴의 item 마우스 focus 시 색 변환
-> 기능 구현은 이제 멈추고 리펙토링 시작, 접근성 수정
어떤 변경 사항이 있나요?
=> feature:포커스색변환, 같이해요드롭다운메뉴 -taewook 01/15오후1:04

src/pages/chat/chat.js, src/pages/exchangeBoard/exchangeBoard.js
feat : 채팅방 구현
- 채팅을 할 수 있는 채팅방 구현
#116
어떤 변경 사항이 있나요?
=> feat : 채팅방 구현 01-15 13:55

src/pages/category/category.js, src/pages/category/index.html, src/pages/login/login.js, src/pages/signUp/signUp.js, src/pages/start/index.html
카테고리 및 회원가입 서버 전송코드 수정
어떤 변경 사항이 있나요?
=> modify : 카테고리 및 회원가입 서버 전송코드 수정 - iamjinpark 01/15 3:35pm

src/pages/chat/chat.js, src/pages/chat/index.html
- 채팅 뿌려주는 순서 고민중
어떤 변경 사항이 있나요?
=> feat : 채팅창 구현중

src/pages/board/board.js, src/pages/board/index.html, src/pages/boardContent/boardContent.js, src/pages/boardContent/index.html, src/pages/togetherBoard/index.html, src/pages/togetherBoard/togetherBoard.js, src/pages/writeBoard/index.html, src/pages/writeBoard/writeBoard.js
modify:주석,연속수정하기 수정  tawook1212 01/15오후3:59
어떤 변경 사항이 있나요?
=> modify:주석,연속수정하기 수정  tawook1212 01/15오후3:59

index.html, src/pages/start/index.html
index.html 파일 수정 (경로 이슈)
어떤 변경 사항이 있나요?
=> modify : index.html 파일 수정 (경로 이슈) - iamjinpark 01/15 4:13pm

src/pages/chat/chat.js
- 실시간으로 채팅을 주고받을수 있음
- 추후, 프로젝트 끝나고 채팅방 구현 후 판매자도 제대로 동작할수 있게 구현 예정
- 날짜, 시간도 구현할 예정
#116
어떤 변경 사항이 있나요?
=> feat : 채팅 내용 구현 01-16 00:18

src/pages/profile/profile.js
=> modify : profile

docs/src/pages/story/index.html
=> modify : docs

src/pages/signUp/index copy.html, src/pages/signUp/signUp copy.js
=> file : docs 파일의 행방을 찾아보자 - iamjinpark 01/24 8:28pm

src/pages/board/index.html, src/pages/search/search.js
featuer: 검색기능 범위추가 및 board에도 연결  +commnity taewook 01/25 오전1:15
1.  board page 에서 검색기능 연결, 
2.  검색 필터링 범위 collection : products 에서 추가로 community 도 필터링 추가 
어떤 변경 사항이 있나요?
=> featuer: 검색기능 범위추가 및 board에도 연결  +commnity taewook 01/25 오전1:15
